name: Scrape Inaportnet Data

on:
  schedule:
    - cron: '0 */3 * * *'  # Setiap 3 jam
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug - List Files
        run: ls -R  # Menampilkan struktur folder

      - name: Run Scraping Script
        run: python gabung.py  # Pastikan file ini ada di root repository
