name: Scraping Setiap 3 Jam

on:
  schedule:
    - cron: '0 */3 * * *'  # Menjalankan setiap 3 jam
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scripts
        run: |
          python scrape.py
          python inaport.py
          python gabung.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update data $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
